services:
  - type: web
    name: pbu-web
    env: node
    plan: starter
    repo: https://github.com/kbeans30/pbu-jersey
    rootDir: .
    buildCommand: unzip -o pbu_repo_modified.zip -d . && cd apps/web && npm install && npm run build
    startCommand: cd apps/web && npm run start
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_PRIMARY_COLOR
        value: "#2E8B57"
      - key: NEXT_PUBLIC_SECONDARY_COLOR
        value: "#FFD700"
      - key: NEXT_PUBLIC_CTA_COLOR
        value: "#FF4500"
  - type: web
    name: pbu-api
    env: python
    plan: starter
    repo: https://github.com/kbeans30/pbu-jersey
    rootDir: .
    buildCommand: unzip -o pbu_repo_modified.zip -d . && cd apps/api && pip install -r requirements.txt
    startCommand: cd apps/api && uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pbu-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: pbu-redis
          type: redis
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
      - key: PRINTFUL_API_KEY
        sync: false
      - key: PRINTFUL_STORE_ID
        sync: false
      - key: PRINTFUL_VARIANT_ID
        sync: false
      - key: PRINTFUL_CHEST_PATCH_URL
        sync: false
  - type: worker
    name: pbu-worker
    env: python
    plan: starter
    repo: https://github.com/kbeans30/pbu-jersey
    rootDir: .
    buildCommand: unzip -o pbu_repo_modified.zip -d . && cd apps/worker && pip install -r requirements.txt
    startCommand: cd apps/worker && rq worker -u $REDIS_URL pbu-jobs
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pbu-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: pbu-redis
          type: redis
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
      - key: PRINTFUL_API_KEY
        sync: false
      - key: PRINTFUL_STORE_ID
        sync: false
      - key: PRINTFUL_VARIANT_ID
        sync: false
      - key: PRINTFUL_CHEST_PATCH_URL
        sync: false
  - type: redis
    name: pbu-redis
    plan: starter
    ipAllowList:
      - source: services

databases:
  - name: pbu-db
    plan: starter
